# Generated by Django 6.0.6 on 2026-07-02 11:13

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spark_id', models.CharField(db_index=True, max_length=50)),
                ('scheme', models.CharField(choices=[('SPARK', 'SPARK'), ('PG-STAR', 'PG-STAR'), ('PDF-STAR', 'PDF-STAR')], db_index=True, max_length=10)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('college_name', models.CharField(max_length=255)),
                ('guide_name', models.CharField(max_length=255)),
                ('student_name', models.CharField(db_index=True, max_length=255)),
                ('year', models.CharField(db_index=True, max_length=20)),
                ('title', models.TextField()),
                ('research_area', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('received', 'Received'), ('selected', 'Selected'), ('awarded', 'Awarded')], db_index=True, max_length=20)),
                ('document', models.FileField(upload_to='proposals/%Y/%m/')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('review_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('cleared', 'Cleared'), ('flagged', 'Flagged Duplicate')], db_index=True, default='unreviewed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scheme', 'status'], name='duplicate_c_scheme_572516_idx'), models.Index(fields=['state', 'year'], name='duplicate_c_state_72f620_idx'), models.Index(fields=['research_area', 'status'], name='duplicate_c_researc_4e504b_idx'), django.contrib.postgres.indexes.GinIndex(fields=['title'], name='title_trgm_idx', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['student_name'], name='student_trgm_idx', opclasses=['gin_trgm_ops'])],
                'constraints': [models.UniqueConstraint(fields=('spark_id', 'scheme'), name='unique_spark_id_per_scheme')],
            },
        ),
        migrations.CreateModel(
            name='DocumentSimilarityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField()),
                ('content_score', models.FloatField(default=0)),
                ('title_score', models.FloatField(default=0)),
                ('student_name_score', models.FloatField(default=0)),
                ('college_score', models.FloatField(default=0)),
                ('match_type', models.CharField(choices=[('content', 'Content Match'), ('student', 'Same Student'), ('both', 'Both')], default='content', max_length=10)),
                ('matching_terms', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_match', to='duplicate_check.researchproposal')),
                ('source_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_source', to='duplicate_check.researchproposal')),
            ],
            options={
                'ordering': ['-overall_score'],
                'indexes': [models.Index(fields=['source_proposal', '-overall_score'], name='duplicate_c_source__c03c60_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_proposal', 'matched_proposal'), name='unique_similarity_pair')],
            },
        ),
    ]
