# Generated by Django 6.0.6 on 2026-07-06 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate_check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsimilarityresult',
            name='check_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentsimilarityresult',
            name='matched_paragraphs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='documentsimilarityresult',
            name='matched_sentences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='documentsimilarityresult',
            name='matched_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentsimilarityresult',
            name='total_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='text_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='documentsimilarityresult',
            name='source_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_source', to='duplicate_check.researchproposal'),
        ),
    ]
