# Generated by Django 6.0.6 on 2026-07-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate_check', '0003_add_session_final_report'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='researchproposal',
            new_name='duplicate_c_session_583ab5_idx',
            old_name='duplicate_c_session_idx',
        ),
    ]
