# Generated by Django 6.0.6 on 2026-07-09 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate_check', '0004_rename_duplicate_c_session_idx_duplicate_c_session_583ab5_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_embedding', models.BinaryField(blank=True, null=True)),
                ('para_embeddings', models.BinaryField(blank=True, null=True)),
                ('paragraphs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='duplicate_check.researchproposal')),
            ],
        ),
    ]
